const modalProduct = [
	{
		id: 0,
		title: "Nike Air Max",
		visibility: "",
		price: 109.99,
		instock: 23,
		category: "men",
		alt: "blue mens nike with grey badge",
		img: "/RunZone/img/shoes/men/niebieski.webp",
		brand: "Nike",
		code: "029",
		points: "211",
		instock: "21",
	},
	{
		id: 1,
		title: "Nike Jordan",
		visibility: "",
		price: 140.79,
		instock: 23,
		category: "men",
		alt: "white-red-black mens nike",
		img: "/RunZone/img/shoes/men/men_nike.webp",
		brand: "Nike",
		code: "032",
		points: "290",
		instock: "13",
	},
	{
		id: 3,
		title: "Adidas Sneak",
		visibility: "",
		price: 120.99,
		instock: 23,
		category: "men",
		alt: "lightblue-white mens adidas",
		img: "/RunZone/img/shoes/men/adidas_men.webp",
		brand: "Adidas",
		code: "098",
		points: "240",
		instock: "15",
	},
	{
		id: 3,
		title: "Nike High",
		visibility: "",
		price: 90.99,
		instock: 23,
		category: "men",
		alt: "black-white mens nike",
		img: "/RunZone/img/shoes/men/men_nike_black.webp",
		brand: "Nike",
		code: "056",
		points: "190",
		instock: "46",
	},
	{
		id: 4,
		title: "Nike Air Max",
		visibility: "",
		price: 109.99,
		instock: 23,
		category: "men",
		alt: "red mens nike with white badge",
		img: "/RunZone/img/shoes/men/red_men.webp",
		brand: "Nike",
		code: "030",
		points: "208",
		instock: "24",
	},
	{
		id: 5,
		title: "Adidas Panthera",
		visibility: "",
		price: 199.99,
		instock: 23,
		category: "men",
		alt: "lightbrown panthera mens adidas",
		img: "/RunZone/img/shoes/men/adidas.webp",
		brand: "Adidas",
		code: "111",
		points: "340",
		instock: "45",
	},
	{
		id: 6,
		title: "Adidas Colorful",
		visibility: "",
		price: 219.99,
		instock: 23,
		category: "women",
		alt: "orange-gray-green-black-white womens adidas",
		img: "/RunZone/img/shoes/women/adidas.webp",
		brand: "Adidas",
		code: "099",
		points: "370",
		instock: "98",
	},
	{
		id: 7,
		title: "Adidas Runner",
		visibility: "",
		price: 89.99,
		instock: 23,
		category: "women",
		alt: "white-pink-black womens adidas",
		img: "/RunZone/img/shoes/women/adidas_2.webp",
		brand: "Adidas",
		code: "056",
		points: "120",
		instock: "11",
	},
	{
		id: 8,
		title: "Adidas Gym",
		visibility: "",
		price: 99.99,
		instock: 23,
		category: "women",
		alt: "black-white-rainbow womens adidas",
		img: "/RunZone/img/shoes/women/adidas_3.webp",
		brand: "Adidas",
		code: "046",
		points: "198",
		instock: "27",
	},
	{
		id: 9,
		title: "Puma High",
		visibility: "shoes__hide",
		price: 79.99,
		instock: 23,
		category: "women",
		alt: "green-white womens puma",
		img: "/RunZone/img/shoes/women/puma_women.webp",
		brand: "Puma",
		code: "085",
		points: "160",
		instock: "22",
	},
	{
		id: 10,
		title: "Puma Colored",
		visibility: "shoes__hide",
		price: 116.99,
		instock: 23,
		category: "women",
		alt: "grey-black-pink-blue womens puma",
		img: "/RunZone/img/shoes/women/puma_women_2.webp",
		brand: "Puma",
		code: "048",
		points: "240",
		instock: "21",
	},
	{
		id: 11,
		title: "New Balance Flick",
		visibility: "shoes__hide",
		price: 179.99,
		instock: 23,
		category: "women",
		alt: "grey-green-white-pink womens new balance",
		img: "/RunZone/img/shoes/women/newbalance.webp",
		brand: "New Balance",
		code: "954",
		points: "300",
		instock: "82",
	},
	{
		id: 12,
		title: "Yeezy Kids",
		visibility: "shoes__hide",
		price: 399.99,
		instock: 23,
		category: "kids",
		alt: "blue-white-black kids shoe",
		img: "/RunZone/img/shoes/kids/black_white.webp",
		brand: "Yeezy",
		code: "067",
		points: "800",
		instock: "4",
	},
	{
		id: 13,
		title: "Jordan's Kid",
		visibility: "shoes__hide",
		price: 189.99,
		instock: 23,
		category: "kids",
		alt: "blue-white kids shoe",
		img: "/RunZone/img/shoes/kids/jordan.webp",
		brand: "Nike",
		code: "001",
		points: "320",
		instock: "27",
	},
	{
		id: 14,
		title: "Nike Lightning",
		visibility: "shoes__hide",
		price: 129.99,
		instock: 23,
		category: "kids",
		alt: "green-pink-white-blue kids nike",
		img: "/RunZone/img/shoes/kids/nike.webp",
		brand: "Nike",
		code: "022",
		points: "120",
		instock: "17",
	},
	{
		id: 15,
		title: "Fire Sneaker",
		visibility: "shoes__hide",
		price: 49.99,
		instock: 23,
		category: "kids",
		alt: "black-white kids shoe",
		img: "/RunZone/img/shoes/kids/fire.webp",
		brand: "Fire",
		code: "033",
		points: "80",
		instock: "5",
	},
	{
		id: 16,
		title: "Nike Football",
		visibility: "shoes__hide",
		price: 119.99,
		instock: 23,
		category: "kids",
		alt: "brown-black kids nike football shoe",
		img: "/RunZone/img/shoes/kids/nike_1.webp",
		brand: "Nike",
		code: "199",
		points: "230",
		instock: "4",
	},
	{
		id: 17,
		title: "Nike Rugby",
		visibility: "shoes__hide",
		price: 129.99,
		instock: 23,
		category: "kids",
		alt: "lime-black kids nike rugby shoe",
		img: "/RunZone/img/shoes/kids/nike_2.webp",
		brand: "Nike",
		code: "046",
		points: "270",
		instock: "7",
	},
];
